// DO NOT EDIT THIS FILE
// run generate_meta.py to generate the meta files

#include "generated/material_asset.generated.cpp"
#include "generated/sprite_animation_asset.generated.cpp"
#include "generated/tile_map_asset.generated.cpp"
#include "generated/tile_set_asset.generated.cpp"
#include "generated/animator_component.generated.cpp"
#include "generated/camera_component.generated.cpp"
#include "generated/light_component.generated.cpp"
#include "generated/transform_component.generated.cpp"
#include "generated/scene_component.generated.cpp"
#include "generated/mesh_renderer.generated.cpp"
#include "generated/sprite_renderer.generated.cpp"
#include "generated/tile_map_renderer.generated.cpp"
