name: CI
run-name: CI/CD Tests triggered by ${{ github.actor }}

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    name: Format
    runs-on: self-hosted
    env:
      PATH: /opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    steps:
      - name: Check Formatting
        uses: actions/checkout@v5
      - run: python3 -m scripts.ci.format

  compile_shaders:
    name: Compile shaders
    runs-on: [self-hosted, macOS]
    steps:
      - name: Compile shaders
        uses: actions/checkout@v5
      - run: python3 -m scripts.ci.compile_shaders

  build_debug:
    name: Build Debug
    needs: format
    runs-on: [self-hosted, macOS]
    env:
      PATH: /opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
    steps:
      - name: Build Debug
        uses: actions/checkout@v5
        with:
          submodules: recursive
          fetch-depth: 0
      - run: python3 -m scripts.ci.build